services:
  frontend:
    build:
      context: ./vue/Breakroom
    container_name: docker_dcaley_frontend
    ports:
      - "5173:5173"  # Expose HTTP port (HTTP traffic) for development or internal use
    networks:
      - app-network
    environment:
      - VUE_APP_BACKEND_URL=https://backend:3000  # Example of backend URL for API calls from frontend
      - VITE_PORT=5173
  
  backend:
    build:
      context: ./express  # Path to the backend Dockerfile (from your description)
    container_name: docker_dcaley_backend
    ports:
      - "3000:3000"  # Expose backend service on port 3000
    networks:
      - app-network
    environment:
      - BACKEND_URL=https://docker.dcaley.prosaurus.com
    env_file:
      - ./express/.env

  reverse-proxy:
    image: nginx:alpine
    volumes:
      - /etc/nginx/nginx-docker.conf:/etc/nginx/nginx.conf
      - /etc/nginx/sites-enabled-docker:/etc/nginx/sites-enabled-docker
      - /home/dallas/prosaurus/express/etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "443:443"  # Expose HTTPS port for reverse proxy to handle SSL
      - "80:80"    # Expose HTTP port (usually used for redirecting to HTTPS)
    environment:
      - NGINX_HOST=docker.dcaley.prosaurus.com
    networks:
      - app-network
    depends_on:
      - frontend
      - backend
    entrypoint: nginx -g 'daemon off;'

networks:
  app-network:
    name: app-network
    driver: bridge
